<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<NoWarn>$(NoWarn);CA2016</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Isopoh.Cryptography.Argon2" Version="2.0.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EchoRoom.Database.Infrastructure\EchoRoom.Database.Infrastructure.csproj" />
  </ItemGroup>

</Project>
