namespace EchoRoom.Shared.Constants.Enums;

public enum ErrorStatusCode
{
    NONE,
    UNAUTHORIZED,
    FORBIDDEN,
    VALIDATION_ERROR,
    INVALID_REFRESH_TOKEN,
    COUNTRY_DOES_NOT_EXIST,
    USER_DOES_NOT_EXIST_EMAIL,
    USER_INVALID_PASSWORD,
    USER_LOCKED_OUT,
    USER_DATA_NOT_FOUND,
    USER_DOES_NOT_EXIST_NICKNAME,
    USER_ALREADY_EXISTS_PHONE,
    USER_ALREADY_EXISTS_NICKNAME,
    USER_ALREADY_HAS_ROLE,
    USER_ROLE_CHANGE_NOT_ALLOWED,
    ROLE_DOES_NOT_EXIST,
    CANNOT_SET_CAN_BE_EDITED_FOR_NON_ADMIN,
    INTERNAL_SERVER_ERROR
}