namespace EchoRoom.Shared.Constants.Enums;

public enum ErrorStatusCode
{
    NONE,
    UNAUTHORIZED,
    FORBIDDEN,
    VALIDATION_ERROR,
    COUNTRY_DOES_NOT_EXIST,
    USER_DOES_NOT_EXIST_EMAIL,
    USER_INVALID_PASSWORD,
    USER_LOCKED_OUT,
    USER_DATA_NOT_FOUND,
    USER_ALREADY_EXISTS_EMAIL,
    USER_ALREADY_EXISTS_PHONE,
    USER_ALREADY_EXISTS_NICKNAME,
    INTERNAL_SERVER_ERROR
}